### ISSUE TITLE
Can not change the motor ID

### ISSUE THREAD

**Issue by minhduy105** [hrc2/blossom-public#1]
Hi 
I do not know what happen, but someone I could not change the motor ID anymore. The motor_cal.py run without error, but the ID did not change. Do you guys have any suggestions about for it?
~Duy

**Comment by psychomugs** [comment]
So the motors are being found in `motor_calib.py` and can be controlled by the script (they move with the prompts) but the ID doesn't change?

Were you able to change the IDs and run the script successfully earlier?

**Comment by minhduy105** [comment]
Yes, the motors are found in motor_calib.py, can be controlled by the script, and do not return any errors, but the ID doesn't change.

Yes, I were able to change the IDs and run the script earlier (around last week) for most of them (motor 1,2,3,5) when I first calibrated them. Then, I think I installed most of the package needed to run the start.py and some package for my project (tensorflow). I originally just installed the pypot to run the calibration.

**Comment by psychomugs** [comment]
Can you try running this script to reset the motor(s)?

```
import pypot.dynamixel as pd
p = pd.get_available_ports()
m = pd.Dxl320IO(p[0],1000000)
motor_id = 1 # change to the motor id you need to reset
m.factory_reset({motor_id})
```

**Comment by minhduy105** [comment]
@psychomugs I ran it. The code worked. I was able to reset the motor ID #2 back to #1. However, I still could not change the motor ID using the code from motor_calib.py afterward. 
Additionally, I also tried it with a different computer and got the same result.

**Comment by psychomugs** [comment]
Let's try spamming the motors to change the ID without any of the calibration control
```
import pypot.dynamixel as pd
p = pd.get_available_ports()
m = pd.Dxl320IO(p[0],1000000)
old_id = 1 # change to current ID
new_id = 2 # change to new ID
while (new_id not in m.scan(range(10))):
    m.change_id({old_id:new_id})
```

**Comment by minhduy105** [comment]
I ran it and nothing happened, the ID still did not change. 
Additionally, would you mind sending the source code for the change_id function.

**Comment by psychomugs** [comment]
Pypot source: https://github.com/poppy-project/pypot/blob/ddb4154897b8f8d143da7be870b62690449febdc/pypot/dynamixel/io/abstract_io.py

**Comment by minhduy105** [comment]
The spamming code worked!!! It was weird, but I needed to plug the USB2AX to my computer first, and then turned on the power for the motor to make it work. 
Note: the reset code did not work after I successfully change the ID, I had to spam it in order to change the ID

**Comment by psychomugs** [comment]
Nice! I'll edit `motor_calib.py`to include the spamming for future use.
