### ISSUE TITLE
Installing new requirement.txt

### ISSUE THREAD

**Issue by jmc-codeless** [hrc2/blossom-public#31]
The requirements.txt file currently in the download package for Python 3.x.x is VERY different from the one that I downloaded in August for 2.7.x.  When installing it, the last three modules are not found in the package:  pycrypto, prettytable, and flask_cors.  The install script states 
"Using cached https://files.pythonhosted.org/packages/.... for each of these three modules.  When the actual install occurs, the script throws 
"Running setup.py install for pycrypto ... error
ERROR:  Command errored out with exit status 1:"
Then the installation throws a bunch of red text and exits.

When running woody in order to reset the motors, flask_cors is needed; but, it is not found by the routine; so, it errors out.  I am stuck and cannot finish building blossom.

**Comment by psychomugs** [comment]
Hi jmc,

Are you installing in a `venv`? Can you post the commands you're using to install the reqs?
Depending on your environment you may need to append `3` at the end of `python` and `pip` in your commands, e.g. `python3` and `pip3`

**Comment by jmc-codeless** [comment]
Hi Michael,

 

Thanks for promptly checking out my issue.  Yes, I am running in a venv with Python 3.7.4 downloaded from the python website.  My laptop is running Windows 10, so, I had to use different commands from what are in the blossom instructions.  What I put in the CLI was:

python -m venv blossom_venv

blossom_venv\Scripts\activate

 

The CLI indicated I was running in the blossom_venv environment

 

I made sure I had the latest version of pip:

pip install -U pip

 

Then, I installed requirements.txt:

pip install -r requirements.txt

 

When I got the error message about not installing pycrypto I tried:

pip install -r requirements.txt --user

and got the same results. (I really don’t know what I’m doing with python, or pip, or anything)

 

The attached png are screen shots of the CLI – zoom in to read it.

 

Thanks again,

Jim

**Comment by psychomugs** [comment]
Looking at the code, `pycrypto` might not be required and I uninstalled it from my `venv` and was still able to run `start.py`. Can you try deleting the `pycrypto` from `requirements.txt` and installing again?

**Comment by psychomugs** [comment]
Upon review, I think that `pycrypto` is necessary to use the phone controller mobile app.

Following advice from [here](https://stackoverflow.com/questions/54142430/how-to-install-pycrypto-for-python-3-7-2), can you try deleting `pycrypto` in `requirements.txt` and run `pip install pycryptodome` instead?

**Comment by jmc-codeless** [comment]
Michael,I think that did it.  I just changed the line in requirements.txt to be "pycryptodome".  The installation script downloaded it and showed completion of it along with pretttytable and flask_cors without any error.  I will need to wait until this evening after work to check it plugged into blossom.Thanks,Jim-----Original Message-----

**Comment by jmc-codeless** [comment]
Michael,

I now have blossom responding to sequence commands!  This is pretty cool.

I need to make ears so there is a weight on the ear clips.

There is a problem with the tower gear not meshing well with the motor gear.  I think the tower is too loose on the 3-D printed clip.  I may have to take it apart and try to tighten it ☹.

 

Is there a GUI command interface?

How do I get sequences to be issued in response to sounds?  I think my laptop has a microphone; I know I can plug one in.  Is that the kind of development that is left up to really good programmers (which I am not)?

 

Thanks, again, for the help getting the requirements installed!

 

Warm regards,

Jim

**Comment by psychomugs** [comment]
Great! Let me know if more issues come up, and I'd recommend trying to get the mobile app working so you can control Blossom with your phone.
